
class Autogenerated {
  int seriesId;
  String title;
  String ad;
  int publishDate;
  String thumbnail;
  String summary;

  List<Episodes> episodes;
  String banner;
  String createDate;
  String updateDate;
  int likes;
  int commentCount;
  int episodeCount;

  bool isFinished;
  bool followedByUser;
  int visitCount;
  int followCount;

  Autogenerated(
      {required this.seriesId,
        required this.title,
        required this.ad,
        required this.publishDate,
        required this.thumbnail,
        required this.summary,

        required this.episodes,
        required this.banner,
        required this.createDate,
        required this.updateDate,
        required this.likes,
        required this.commentCount,
        required this.episodeCount,

        required  this.isFinished,
        required this.followedByUser,
        required this.visitCount,
        required this.followCount,
       });

  factory Autogenerated .fromJson(Map<String, dynamic> json) {
    return Autogenerated(seriesId : json['seriesId'],
        title : json['title'],
        ad : json['ad'],
        publishDate : json['publishDate'],
        thumbnail : json['thumbnail'],
        summary : json['summary'],

      episodes :
      json['episodes'],

    banner : json['banner'],
    createDate : json['createDate'],
    updateDate : json['updateDate'],
    likes : json['likes'],
    commentCount : json['commentCount'],
    episodeCount : json['episodeCount'],

    isFinished : json['isFinished'],
    followedByUser : json['followedByUser'],
    visitCount : json['visitCount'],
    followCount : json['followCount']);
 /*   seriesId = json['seriesId'];
    title = json['title'];
    ad = json['ad'];
    publishDate = json['publishDate'];
    thumbnail = json['thumbnail'];
    summary = json['summary'];

    if (json['episodes'] != null) {
      episodes = <Episodes>[];
      json['episodes'].forEach((v) {
        episodes.add(new Episodes.fromJson(v));
      });
    }
    banner = json['banner'];
    createDate = json['createDate'];
    updateDate = json['updateDate'];
    likes = json['likes'];
    commentCount = json['commentCount'];
    episodeCount = json['episodeCount'];

    isFinished = json['isFinished'];
    followedByUser = json['followedByUser'];
    visitCount = json['visitCount'];
    followCount = json['followCount'];
    if (json['bundleIds'] != null) {

    }*/
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['seriesId'] = this.seriesId;
    data['title'] = this.title;
    data['ad'] = this.ad;
    data['publishDate'] = this.publishDate;
    data['thumbnail'] = this.thumbnail;
    data['summary'] = this.summary;

    if (this.episodes != null) {
      data['episodes'] = this.episodes.map((v) => v.toJson()).toList();
    }
    data['banner'] = this.banner;
    data['createDate'] = this.createDate;
    data['updateDate'] = this.updateDate;
    data['likes'] = this.likes;
    data['commentCount'] = this.commentCount;
    data['episodeCount'] = this.episodeCount;

    data['isFinished'] = this.isFinished;
    data['followedByUser'] = this.followedByUser;
    data['visitCount'] = this.visitCount;
    data['followCount'] = this.followCount;

    return data;
  }
}



class Episodes {
  int episodeId;
  String number;
  String title;
  String thumbnail;
  int seriesId;
  int price;
  bool isBought;
  int commentCount;
  int likes;

  Episodes(
      {required this.episodeId,
        required this.number,
        required this.title,
        required this.thumbnail,
        required this.seriesId,
        required this.price,
        required this.isBought,
        required  this.commentCount,
        required  this.likes});

  factory Episodes.fromJson(Map<String, dynamic> json) {
    return Episodes(
        episodeId : json['episodeId'],
        number : json['number'],
        title : json['title'],
        thumbnail : json['thumbnail'],
        seriesId : json['seriesId'],
        price : json['price'],
        isBought : json['isBought'],
        commentCount : json['commentCount'],
        likes : json['likes']
    );

  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['episodeId'] = this.episodeId;
    data['number'] = this.number;
    data['title'] = this.title;
    data['thumbnail'] = this.thumbnail;
    data['seriesId'] = this.seriesId;
    data['price'] = this.price;
    data['isBought'] = this.isBought;
    data['commentCount'] = this.commentCount;
    data['likes'] = this.likes;
    return data;
  }
}

